# Generated by Django 2.0.7 on 2019-10-27 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedtext',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.TextField(verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
