# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjRouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('active', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
            ],
        ),
        migrations.AddField(
            model_name='projrouts',
            name='rout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Rout'),
        ),
        migrations.AddField(
            model_name='project',
            name='routs',
            field=models.ManyToManyField(through='Manuals.ProjRouts', to='Manuals.Rout'),
        ),
    ]
