# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_time', models.DateTimeField(verbose_name='date published')),
                ('last_lat', models.FloatField(verbose_name='Широта')),
                ('last_lon', models.FloatField(verbose_name='Долгота')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Project')),
                ('rout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Rout')),
            ],
        ),
    ]
