# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0002_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='last_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 9, 15, 15, 908743, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Project', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='object',
            name='rout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Rout', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projrouts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Project', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='projrouts',
            name='rout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manuals.Rout', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='rout',
            name='active',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rout',
            name='name',
            field=models.CharField(max_length=5, verbose_name='Наименование'),
        ),
    ]
