# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0003_auto_20160323_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='last_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 11, 18, 1, 346202, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rout',
            name='active',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], verbose_name='Статус'),
        ),
    ]
