# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0004_auto_20160323_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 12, 2, 3, 758905, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
    ]
