# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0005_auto_20160323_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='year_release',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 12, 20, 26, 458435, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
    ]
