# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0006_auto_20160323_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='date_inserted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 13, 7, 44, 95549, tzinfo=utc), verbose_name='Дата добавление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 7, 26, 637063, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
        migrations.AlterField(
            model_name='object',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
