# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0007_auto_20160323_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rout',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='rout',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='routs',
            new_name='routes',
        ),
        migrations.RenameField(
            model_name='projrouts',
            old_name='rout',
            new_name='route',
        ),
        migrations.AlterField(
            model_name='object',
            name='date_inserted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 37, 4, 681319, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
    ]
