# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0008_auto_20160323_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='output',
            field=models.BooleanField(choices=[(1, 'Выведен'), (0, 'Активен')], default=0, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='object',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 52, 21, 760886, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 52, 21, 760886, tzinfo=utc), verbose_name='Последнее время отклика'),
        ),
    ]
