# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0009_auto_20160323_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='date_inserted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='object',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее время отклика'),
        ),
    ]
