# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manuals', '0011_auto_20160324_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name_proj',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='name_route',
            new_name='name',
        ),
    ]
