# Generated by Django 2.2.13 on 2020-07-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='is_actived',
            new_name='is_activated',
        ),
    ]
